### ISSUE TITLE
Windows: Prohibited directory and file names

### ISSUE THREAD

**Issue by jjsquad** [banago/PHPloy#246]
HI!
When I phploy on my OSX system, all flys like a charm. 
On my Windows system I receive this following errors:

Prohibited directory name in phar: 'vendor\somedirectory' error on line 321 in Ftp.php
and
Prohibited file name in phar: 'vendor\autoload.php' error on line 211 in Ftp.php

How I can resolve this?
I create a fork and in src/PHPloy.php I've changed '/' strings to DIRECTORY_SEPARATOR const, but the error continues.

Sorry for my bad english.
:)

**Comment by jjsquad** [comment]
Hi! Again! :D 
I resolved this issue: reaplacing the all DIRECTORY_SEPARATOR on PHPloy.php file to '/'.

I'll put this in a future PR.

Thank you.

**Comment by EpocDotFr** [comment]
I have the same issue. It is blocking, sadly.

I suggest using the [`DIRECTORY_SEPARATOR`](http://php.net/manual/en/dir.constants.php) PHP constant directly.

**Comment by EpocDotFr** [comment]
Same blocking issue here.

**Comment by banago** [comment]
@jjsquad yes please, create a PR. Thanks.

**Comment by EpocDotFr** [comment]
@jjsquad Are you using the native Windows shell? Or a wrapper like Cygwin?

**Comment by EpocDotFr** [comment]
@jjsquad Yeah but don't replace **all** `DIRECTORY_SEPARATOR` by a `/`, only those concerning a remote path.

**Comment by banago** [comment]
@jjsquad can you paste here a full error message you get?

**Comment by banago** [comment]
@jjsquad and @EpocDotFr please grab latest version and test again. This should now be fixed. Please reopen the ticket if you run again into it.

**Comment by jjsquad** [comment]
I'll do it. Thanks!

**Comment by EpocDotFr** [comment]
> PHPloy v4.3.1

This issue is still happening for me, but not for all files.

> Warning: ftp_fput(): Prohibited file name: vendor\autoload.php in phar://F:/www/notes/phploy/vendor/league/flysystem/src/Adapter/Ftp.php on line 211
 ! Failed to upload vendor\autoload.php.

> Warning: ftp_mkdir(): Prohibited directory name in phar://F:/www/notes/phploy/vendor/league/flysystem/src/Adapter/Ftp.php on line 321

> Warning: ftp_fput(): Prohibited file name: vendor\composer\autoload_files.php in phar://F:/www/notes/phploy/vendor/league/flysystem/src/Adapter/Ftp.php on line 211
 ! Failed to upload vendor\composer\autoload_files.php.

**Comment by jjsquad** [comment]
I see. But I think that problem its located at lines, 1276, 1278, 1281, 1286 in PHPloy.php file. 

Changing DIRECTORY_SEPARATOR in this lines can solve this warnings. 
Try it.

I cant test this now, but soon as I can, I`m back here and report.
Cya!

**Comment by banago** [comment]
@jjsquad you're so right. Just updated PHPloy. Grab latest version please.

**Comment by EpocDotFr** [comment]
Works like a charm now \o/
